version: "3.9"

services:
  postgres:
    container_name: postgres_ln_service
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ln-withdraw-usr
      POSTGRES_PASSWORD: ln-withdraw-pwd
      POSTGRES_DB: ln-withdraw
